spring:
  application:
    name: skufservices
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
    hibernate:
      ddl-auto:
    show-sql: false
server:
  error:
    whitelabel:
      enabled: false
security:
  token: f5fe55757d52de7095b432b04a0edd6ba322a7a832e27c4617aee8414325d4e119aff6687db964e7cdbc22ad0d61b2fa43589126196560182ff07c07628218b2
  expiration-time-ms: 6000000000000000000

